export const SET_CLIENTS = 'SET_CLIENTS'
export const UPDATE_DRAFT = 'UPDATE_DRAFT'
export const DROP_DRAFT = 'DROP_DRAFT'
export const CREATE_DRAFT = 'CREATE_DRAFT'
export const HAS_TOKEN = 'HAS_TOKEN'
