<template>
  <b-container fluid class="p-1">
    <b-row>
      <b-col>
        <b-card no-body footer-class="p-0">
          <b-tabs
            v-model="tabSelected"
            card
          >
            <b-tab
              v-for="tab in tabs"
              :key="`tab-${tab}}`"
              class="p-0"
            >
              <template v-slot:title>
                <div class="close-container">
                  <b-spinner v-if="isBusy" small />
                  <b-icon-file-text v-else />
                  {{ tab }}
                  <b-btn
                    @click="onClose(tab)"
                    size="sm"
                    variant="outline-tertiary"
                    class="close-tab"
                  >
                    <b-icon-x />
                  </b-btn>
                </div>
              </template>
              <!-- <b-btn
                v-b-toggle="`${tab}-collapse`"
                variant="outline-secondary"
                pill
                class="px-2 mb-3"
              >
                <b-icon-building />
              </b-btn>
              <b-collapse
                :id="`${tab}-collapse`"
                class="mt-2"
              >
                <client-selector />
              </b-collapse> -->
              <da-note :tab="tab" :clients="clients" />
            </b-tab>
            <template v-slot:tabs-end>
              <b-nav-item
                id="add-new"
                role="presentation"
                @click.prevent="newTab"
                class="add-btn shake-bottom"
              >
                <b-icon-plus />
              </b-nav-item>
            </template>
            <template v-slot:empty>
              <div class="text-center text-muted">
                There are no open notes.<br>
                Create a new note using the <b>+</b> button above.
              </div>
            </template>
          </b-tabs>
          <!-- <template v-slot:footer>
            <b-btn @click="getClients" variant="tertiary">
              Action 2
            </b-btn>
            <b-btn @click="getClients" variant="quaternary" class="roman">
              Action 3
            </b-btn>
          </template> -->
        </b-card>
      </b-col>
    </b-row>
  </b-container>
</template>

<script>
import DaNote from '../../components/da-note'
import ClientSelector from '../../components/client-selector'
export default {
  components: {
    DaNote,
    ClientSelector
  },
  data () {
    return {
      isBusy: false,
      tabs: [],
      tabCounter: 0,
      tabSelected: 1,
      // client: null,
      // clients: [],
      res: []
    }
  },
  computed: {
    all() {
      return this.$store.state
    }
  },
  methods: {
    newTab() {
      chrome.storage.sync.set({
        tabCounter: this.tabCounter
      }, (res) => console.log({ res }))
      this.tabs.push(this.tabCounter++)
    },
    onClose(x) {
      for (let i = 0; i < this.tabs.length; i++) {
        if (this.tabs[i] === x) {
          this.tabs.splice(i, 1)
        }
      }
    }
  }
}
</script>

<style lang="scss" scoped>
@import url('https://fonts.googleapis.com/css2?family=Vollkorn:ital,wght@1,700&display=swap');
.roman {
  font-family: 'Vollkorn', 'Times New Roman', Times, serif;
  font-style: italic;
  font-weight: 700;
}
.close-container {
  position: relative;
  & .close-tab {
    position: absolute;
    right: 0;
    border-radius: 50%;
    padding: 0 0.05em;
    transform: translate(75%, -275%);
    transition: all 200ms ease;
    opacity: 0;
    transition-delay: 100ms;;
  }
  &:hover .close-tab {
    transform: translate(75%, -75%);
    opacity: 1;
  }
}
.add-btn {
  position: relative;
  border: none;
  margin-left: 0.15em;
  padding: 0;
  transition: 200ms ease-in-out;
  &:hover,
  &:active {
    background-color: #dee2e6;
    border: none;
    outline: none;
    & .nav-link::after {
      position: absolute;
      left: 50%;
      transform: translate(-50%, -50%);
      height: 100%;
      content: "add";
    }
  }
  & .nav-link {
    padding-left: 0.25em;
    padding-right: 0.25em;
  }
}
.shake-bottom {
  animation: shake-bottom 0.8s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-4-28 14:22:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation shake-bottom
 * ----------------------------------------
 */
@keyframes shake-bottom {
  0%,
  100% {
    transform: rotate(0deg);
    transform-origin: 50% 100%;
  }
  10% {
    transform: rotate(2deg);
  }
  20%,
  40%,
  60% {
    transform: rotate(-4deg);
  }
  30%,
  50%,
  70% {
    transform: rotate(4deg);
  }
  80% {
    transform: rotate(-2deg);
  }
  90% {
    transform: rotate(2deg);
  }
}
</style>
