<template>
  <b-container fluid class="p-1 my-2">
    <b-row no-gutters>
      <b-col>
        <b-card no-body footer-class="p-0">
          <b-tabs
            card
          >
            <b-tab
              v-for="tab in drafts"
              :key="`tab-${tab.id}`"
              class="p-0"
            >
              <template v-slot:title>
                <div class="close-container">
                  <b-icon-file-text />
                  {{ tab.id }}
                  <b-btn
                    @click="onClose(tab.id)"
                    size="sm"
                    variant="outline-tertiary"
                    class="close-tab"
                  >
                    <b-icon-x />
                  </b-btn>
                </div>
              </template>
              <da-note :tab="tab" />
            </b-tab>
            <template v-slot:tabs-end>
              <b-nav-item
                id="add-new"
                role="presentation"
                @click.prevent="newTab"
                class="add-btn shake-bottom"
              >
                <b-icon-plus />
              </b-nav-item>
            </template>
            <template v-slot:empty>
              <div class="text-center text-muted">
                There are no open notes.<br>
                Create a new note using the <b>+</b> button above.
              </div>
            </template>
          </b-tabs>
        </b-card>
      </b-col>
    </b-row>
  </b-container>
</template>

<script>
import DaNote from '../../components/da-note'
import ClientSelector from '../../components/client-selector'
export default {
  components: {
    DaNote,
    ClientSelector
  },
  data () {
    return {
      isBusy: false,
      // tabs: [],
      // tabCounter: 0,
      // tabSelected: 1,
      res: []
    }
  },
  computed: {
    drafts() {
      return this.$store.getters.drafts
    },
    tabCounter() {
      return this.drafts.length
    }
  },
  methods: {
    newTab() {
      // this.tabCounter = this.tabCounter + 1
      // this.tabs.push(this.tabCounter++)
      chrome.runtime.sendMessage({
        msg: 'createDraft',
        data: {
          id: this.tabCounter + 1,
          urn: '',
          locations: [],
          category: null,
          actionType: null,
          isInternal: true,
          annotation: {
            html: '',
            json: ''
          }
        }
      })
    },
    onClose(x) {
      for (let i = 0; i < this.tabs.length; i++) {
        if (this.drafts[i] === x.id) {
          // this.tabs.splice(i, 1)
          this.$store.dispatch('dropDraft', i)
        }
      }
    }
  }
}
</script>

<style lang="scss" scoped>
@import url('https://fonts.googleapis.com/css2?family=Vollkorn:ital,wght@1,700&display=swap');
.roman {
  font-family: 'Vollkorn', 'Times New Roman', Times, serif;
  font-style: italic;
  font-weight: 700;
}
.close-container {
  position: relative;
  & .close-tab {
    position: absolute;
    right: 0;
    border-radius: 50%;
    padding: 0 0.05em;
    transform: translate(75%, -275%);
    transition: all 200ms ease;
    opacity: 0;
    transition-delay: 100ms;;
  }
  &:hover .close-tab {
    transform: translate(75%, -75%);
    opacity: 1;
  }
}
.add-btn {
  position: relative;
  border: none;
  margin-left: 0.15em;
  padding: 0;
  transition: 200ms ease-in-out;
  &:hover,
  &:active {
    background-color: #dee2e6;
    border: none;
    outline: none;
    & .nav-link::after {
      position: absolute;
      left: 50%;
      transform: translate(-50%, -50%);
      height: 100%;
      content: "add";
    }
  }
  & .nav-link {
    padding-left: 0.25em;
    padding-right: 0.25em;
  }
}
.shake-bottom {
  animation: shake-bottom 0.8s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-4-28 14:22:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation shake-bottom
 * ----------------------------------------
 */
@keyframes shake-bottom {
  0%,
  100% {
    transform: rotate(0deg);
    transform-origin: 50% 100%;
  }
  10% {
    transform: rotate(2deg);
  }
  20%,
  40%,
  60% {
    transform: rotate(-4deg);
  }
  30%,
  50%,
  70% {
    transform: rotate(4deg);
  }
  80% {
    transform: rotate(-2deg);
  }
  90% {
    transform: rotate(2deg);
  }
}
</style>
