<template>
  <b-card
    :bg-variant="isInternal ? 'quaternary-lt4' : 'white'"
    class="border-0 py-1 note"
    header-class="p-0"
    footer-class="p-0"
    footer-bg-variant="white"
  >
    <template v-slot:header>
      <div class="d-flex w-100 justify-content-start menubar">
        <b-btn
          :id="`hub-toggle-${tab}`"
          v-b-toggle="`${tab}-collapse`"
          :variant="`${clientComplete ? 'success' : 'outline-primary'}`"
          class="px-2 shake-vertical"
        >
          <b-icon-building />
        </b-btn>
        <div class="menubar__spacer bg-primary" />
        <div class="bg-primary text-white d-flex align-items-center px-3">
          <b-spinner v-show="!draftSaved" small />
        </div>
        <b-btn
          @click="draftSaved = !draftSaved"
          variant="outline-primary"
          class="menubar__btn draft-btn"
        >
          <b-icon-file-earmark-diff v-if="!draftSaved" />
          <b-icon-file-earmark-check v-else />
        </b-btn>
        <b-btn variant="outline-primary" class="menubar__btn">
          <b-icon-bookmark />
        </b-btn>
        <b-btn variant="outline-primary" class="menubar__btn">
          <b-icon-trash />
        </b-btn>
      </div>
    </template>
    <div class="pb-3 pt-1">
      <b-collapse
        :id="`${tab}-collapse`"
        visible
      >
        <client-selector @hub-ready="clientComplete = !clientComplete" />
      </b-collapse>
    </div>
    <b-form-group class="text-secondary">
      <template v-slot:label>
        <b-icon-file-richtext />
        Note
      </template>
      <text-area
        :theme="theme"
        :content="content.html"
        @text-update="onUpdate"
      />
    </b-form-group>
    <b-form-checkbox
      v-model="isInternal"
      switch
      size="sm"
      class="my-3"
    >
      <b-icon-eye-fill v-if="!isInternal" />
      <b-icon-eye-slash v-else />
      {{ isInternal ? 'Internal-Only' : 'Ok to Share' }}
    </b-form-checkbox>
    {{ content.html }}
  </b-card>
</template>

<script>
import ClientSelector from './client-selector'
import TextArea from './text-area'
export default {
  components: {
    ClientSelector,
    TextArea
  },
  props: ['tab', 'clients'],
  data() {
    return {
      client: null,
      clientComplete: false,
      content: {
        html: '',
        json: null
      },
      isInternal: false,
      draftSaved: true,
      theme: 'secondary'
    }
  },
  afterCreated() {
    this.toggleShowStart()
  },
  methods: {
    onUpdate(payload) {
      console.log({ payload })
      this.content = payload
    }
  }
}
</script>

<style lang="scss" scoped>
.note {
  &__content {
    font-size: 0.9em;
  }
  & .menubar {
    // margin-bottom: 0.75em;
    box-shadow: 0 5px 5px rgba(0, 0, 0, 0.2);
    transition: 200ms ease-out;
    display: flex;
    &:hover {
      box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
    }
    &__spacer {
      flex: 1 1 auto;
    }
    &__btn {
      position: relative;
      padding: 0.15em 0.25em;
      margin: 0;
      & .is-active {
        background-color: #0b233f;
        color: white;
      }
      &:hover {
        &.draft-btn::after {
          content: 'save';
          position: absolute;
          color: #0b233f;
          left: 50%;
          transform: translate(-50%, -80%);
          height: 100%;
        }
      }
    }
  }
}
.shake-vertical {
  animation: shake-vertical 0.8s cubic-bezier(0.455, 0.030, 0.515, 0.955) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-4-28 14:27:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation shake-vertical
 * ----------------------------------------
 */
@keyframes shake-vertical {
  0%,
  100% {
    transform: translateY(0);
  }
  10%,
  30%,
  50%,
  70% {
    transform: translateY(-4px);
  }
  20%,
  40%,
  60% {
    transform: translateY(4px);
  }
  80% {
    transform: translateY(2px);
  }
  90% {
    transform: translateY(-2.2px);
  }
}

</style>
